---
- name: Install dependencies
  tags:
    - dependencies
  when:
    - pve_kvm_apt_dependencies_install | bool
    - pve_kvm_apt_dependencies_list is defined
    - pve_kvm_apt_dependencies_list is iterable
  ansible.builtin.include_tasks:
    file: sub-tasks/dependencies.yml


- name: Get kvm vmid
  ansible.builtin.include_tasks:
    file: sub-tasks/kvm_get_vmid.yml


- name: Poweron qemu kvm {{ kvm.name }}
  when:
    - vmid is defined
    - vmid | int
  delegate_to: "{{ kvm.api_host }}"
  ignore_errors: true
  community.general.proxmox_kvm:
    node: "{{ kvm.node }}"
    api_host: "{{ kvm.api_host }}"
    api_user: "{{ kvm.api_user | default(pve_kvm_global_api_user) | default(omit) }}"
    api_password: "{{ kvm.api_password | default(pve_kvm_global_api_password) | default(omit) }}"
    api_token_id: "{{ kvm.api_token_id | default(pve_kvm_global_api_token_id) | default(omit) }}"
    api_token_secret: "{{ kvm.api_token_secret | default(pve_kvm_global_api_token_secret) | default(omit) }}"
    validate_certs: "{{ kvm.validate_certs | default(pve_kvm_global_validate_certs) | default(omit) }}"
    timeout: "{{ kvm.timeout | default(pve_kvm_global_timeout) | default(omit) }}"
    vmid: "{{ vmid }}"
    state: started
